## Data Augmentation

#### Objective: augment the jobs df in the following ways:
        1) include aggregate income data based on zip code
        2)

In [1]:
zip_text= """
#	Zip Code	Location	City	Population	Avg. Income/H/hold	National Rank
1.	92130	32.957195, -117.202542	San Diego, California	28,187	$93,929.00	#372
2.	92131	32.893250, -117.087091	San Diego, California	29,279	$90,811.00	#440
3.	92129	32.961064, -117.134917	San Diego, California	47,217	$77,851.00	#943
4.	92127	33.017518, -117.118456	San Diego, California	20,032	$75,219.00	#1,098
5.	92121	32.898613, -117.202937	San Diego, California	4,248	$70,750.00	#1,463
6.	92128	33.000269, -117.072093	San Diego, California	42,728	$66,676.00	#1,918
7.	92106	32.713460, -117.236378	San Diego, California	18,505	$62,121.00	#2,537
8.	92126	32.886925, -117.152162	San Diego, California	74,222	$60,229.00	#2,969
9.	92124	32.827238, -117.089287	San Diego, California	30,187	$59,164.00	#3,164
10.	92120	32.807867, -117.060993	San Diego, California	25,553	$57,461.00	#3,497
11.	92119	32.802959, -117.027095	San Diego, California	21,850	$55,973.00	#3,871
12.	92122	32.857230, -117.209774	San Diego, California	34,891	$52,039.00	#5,040
13.	92123	32.808814, -117.134694	San Diego, California	25,217	$49,646.00	#6,070
14.	92139	32.677716, -117.047666	San Diego, California	36,341	$49,032.00	#6,302
15.	92117	32.825086, -117.199424	San Diego, California	51,203	$47,245.00	#7,069
16.	92114	32.707892, -117.055120	San Diego, California	66,837	$46,189.00	#7,664
17.	92109	32.787836, -117.232376	San Diego, California	46,071	$45,202.00	#8,262
18.	92154	32.578103, -117.012975	San Diego, California	68,764	$42,970.00	#9,563
19.	92111	32.805518, -117.169052	San Diego, California	46,821	$42,774.00	#9,691
20.	92107	32.741852, -117.243453	San Diego, California	27,956	$42,660.00	#9,770
21.	92108	32.774046, -117.142454	San Diego, California	11,640	$42,626.00	#9,790
22.	92110	32.765010, -117.199380	San Diego, California	24,149	$40,642.00	#11,487
23.	92103	32.747484, -117.166877	San Diego, California	30,186	$39,578.00	#12,506
24.	92116	32.765299, -117.122565	San Diego, California	33,080	$35,401.00	#17,001
25.	92115	32.762506, -117.072450	San Diego, California	56,883	$31,666.00	#21,440
26.	92104	32.741499, -117.127409	San Diego, California	47,688	$31,139.00	#22,144
27.	92102	32.716007, -117.117462	San Diego, California	47,123	$26,505.00	#27,101
28.	92105	32.741859, -117.090353	San Diego, California	72,994	$25,593.00	#27,821
29.	92113	32.697098, -117.116587	San Diego, California	47,417	$23,841.00	#28,897
30.	92101	32.725230, -117.171346	San Diego, California	27,494	$23,762.00	#28,929
"""

In [2]:
import pandas as pd
import numpy as np

In [3]:
temp = list()
for i in zip_text.splitlines()[2:]:
    temp.append(i.split('\t'))

In [4]:
temp_df = pd.DataFrame(temp)
temp_df.head()

,0,1,2,3,4,5,6
0,1.,92130,"32.957195, -117.202542","San Diego, California","28,187","$93,929.00",#372
1,2.,92131,"32.893250, -117.087091","San Diego, California","29,279","$90,811.00",#440
2,3.,92129,"32.961064, -117.134917","San Diego, California","47,217","$77,851.00",#943
3,4.,92127,"33.017518, -117.118456","San Diego, California","20,032","$75,219.00","#1,098"
4,5.,92121,"32.898613, -117.202937","San Diego, California","4,248","$70,750.00","#1,463"

In [5]:
temp_cols = []
for i in zip_text.splitlines()[0:2]:
    temp_cols.append(i.split('\t'))

In [6]:
temp_cols = [item for sublist in temp_cols for item in sublist]

In [7]:
temp_cols.pop(0)

''

In [8]:
temp_df.columns = temp_cols

In [9]:
temp_df.drop(columns = ['#', 'City'], inplace = True)

In [10]:
#Splitting Location column into two (Latitude and Longitude)
location_df = pd.DataFrame(list(map(lambda x: x.split(', '), temp_df.Location)), columns = ['Latitude', 'Longitude'])
zip_wealth = pd.concat([location_df, temp_df], join='outer', axis = 1)
zip_wealth.drop(columns = ['Location'], inplace = True)

In [11]:
#Simplifying column name
zip_wealth.rename(columns = {'Avg. Income/H/hold':'Avg Income'}, inplace = True)

In [12]:
# Cleaning up - removing symbols
zip_wealth['Avg Income'] = list(map(lambda x: x[:-3].strip('$').replace(',', ''), zip_wealth['Avg Income']))
zip_wealth['National Rank'] = list(map(lambda x: x.strip('#').replace(',',''), zip_wealth['National Rank']))

In [13]:
zip_wealth['Population'] = list(map(lambda x: x.replace(',',''), zip_wealth['Population']))

In [14]:
zip_wealth.head()

    Latitude    Longitude Zip Code Population Avg Income National Rank
0  32.957195  -117.202542    92130      28187      93929           372
1  32.893250  -117.087091    92131      29279      90811           440
2  32.961064  -117.134917    92129      47217      77851           943
3  33.017518  -117.118456    92127      20032      75219          1098
4  32.898613  -117.202937    92121       4248      70750          1463

In [15]:
#Finally, fixing data types:
zip_wealth.dtypes

Latitude         object
Longitude        object
Zip Code         object
Population       object
Avg Income       object
National Rank    object
dtype: object

In [16]:
zip_wealth.astype('float64')

     Latitude   Longitude  Zip Code  Population  Avg Income  National Rank
0   32.957195 -117.202542   92130.0     28187.0     93929.0          372.0
1   32.893250 -117.087091   92131.0     29279.0     90811.0          440.0
2   32.961064 -117.134917   92129.0     47217.0     77851.0          943.0
3   33.017518 -117.118456   92127.0     20032.0     75219.0         1098.0
4   32.898613 -117.202937   92121.0      4248.0     70750.0         1463.0
5   33.000269 -117.072093   92128.0     42728.0     66676.0         1918.0
6   32.713460 -117.236378   92106.0     18505.0     62121.0         2537.0
7   32.886925 -117.152162   92126.0     74222.0     60229.0         2969.0
8   32.827238 -117.089287   92124.0     30187.0     59164.0         3164.0
9   32.807867 -117.060993   92120.0     25553.0     57461.0         3497.0
10  32.802959 -117.027095   92119.0     21850.0     55973.0         3871.0
11  32.857230 -117.209774   92122.0     34891.0     52039.0         5040.0
12  32.808814 -117.134694   92123.0     25217.0     49646.0         6070.0
13  32.677716 -117.047666   92139.0     36341.0     49032.0         6302.0
14  32.825086 -117.199424   92117.0     51203.0     47245.0         7069.0
15  32.707892 -117.055120   92114.0     66837.0     46189.0         7664.0
16  32.787836 -117.232376   92109.0     46071.0     45202.0         8262.0
17  32.578103 -117.012975   92154.0     68764.0     42970.0         9563.0
18  32.805518 -117.169052   92111.0     46821.0     42774.0         9691.0
19  32.741852 -117.243453   92107.0     27956.0     42660.0         9770.0
20  32.774046 -117.142454   92108.0     11640.0     42626.0         9790.0
21  32.765010 -117.199380   92110.0     24149.0     40642.0        11487.0
22  32.747484 -117.166877   92103.0     30186.0     39578.0        12506.0
23  32.765299 -117.122565   92116.0     33080.0     35401.0        17001.0
24  32.762506 -117.072450   92115.0     56883.0     31666.0        21440.0
25  32.741499 -117.127409   92104.0     47688.0     31139.0        22144.0
26  32.716007 -117.117462   92102.0     47123.0     26505.0        27101.0
27  32.741859 -117.090353   92105.0     72994.0     25593.0        27821.0
28  32.697098 -117.116587   92113.0     47417.0     23841.0        28897.0
29  32.725230 -117.171346   92101.0     27494.0     23762.0        28929.0

In [22]:
jobs_df = pd.read_csv('VectorMovingJobs.csv')
jobs_df = jobs_df.iloc[:,2:] #Removed columns reflecting index

In [26]:
jobs_df.shape

(4015, 32)

In [24]:
jobs_df.isna().sum() #lots of nulls unfortunately

DTSTART                   225
DTEND                     226
RRULE                    3993
DTSTAMP                   225
UID                       225
CREATED                   225
DESCRIPTION               763
ORIGIN                   2326
ORIGIN TYPE              3965
ORIGIN ZIP CODE          3572
DESTINATION              2387
DESTINATION TYPE         4015
DESTINATION ZIP CODE     3606
SIZE                     2392
CREW                     2368
NUMBER OF MOVERS         2429
TRUCKS                   2421
NUMBER OF TRUCKS         3917
RATE                     2335
CUSTOMER NAME            2328
CUSTOMER PHONE           2321
CUSTOMER EMAIL           1573
LAST MODIFIED             225
LOCATION                 2790
SEQUENCE                  225
SUMMARY                   226
CANCELLED                 225
TRANSP                    225
ORIGIN LATITUDE          2352
ORIGIN LONGITUDE         2352
DESTINATION LATITUDE     2589
DESTINATION LONGITUDE    2589
dtype: int64

In [31]:
jobs_df

,DTSTART,DTEND,RRULE,DTSTAMP,UID,CREATED,DESCRIPTION,ORIGIN,ORIGIN TYPE,ORIGIN ZIP CODE,...,LAST MODIFIED,LOCATION,SEQUENCE,SUMMARY,CANCELLED,TRANSP,ORIGIN LATITUDE,ORIGIN LONGITUDE,DESTINATION LATITUDE,DESTINATION LONGITUDE
0,2013-08-17 15:00:00,2013-08-17 16:00:00,NaN,2016-11-29 12:31:58,ADD8F2DD-BFEC-4BF8-935F-D8AC24FCBBA8,2013-08-16 00:08:29,7 hours =$975\n15%=$146.25\nJllano@sdsp.net,NaN,NaN,NaN,...,2013-08-18 17:53:08,972 broadway 91911 building bihind 970 to 2811...,0.0,$130/hr $65 gas John Llano 619-520-3564\; 619-...,0.0,OPAQUE,NaN,NaN,NaN,NaN
1,2013-08-18 22:00:00,2013-08-18 23:00:00,NaN,2016-11-29 12:31:58,5BB18929-7974-4C88-9C53-95588D841D7D,2013-08-18 17:35:50,4:15 $306\n15%- $46.00,NaN,NaN,NaN,...,2013-08-19 20:27:06,7864 avenida navidad San Diego 92122 #195 to 8...,0.0,$65 $30 kar khe 832-466-5649 858-663-5613,0.0,OPAQUE,NaN,NaN,NaN,NaN
2,2013-08-18 20:30:00,2013-08-18 21:30:00,NaN,2016-11-29 12:31:58,97vcl68nn3potk63j78ds7vs54@google.com,2013-08-19 20:31:03,NaN,NaN,NaN,NaN,...,2013-08-19 20:31:03,NaN,0.0,Send 146.25+46= 192.25,0.0,OPAQUE,NaN,NaN,NaN,NaN
3,2013-08-19 19:00:00,2013-08-19 20:00:00,NaN,2016-11-29 12:31:58,B7461062-4494-4A2D-8E78-5538A8E980DD,2013-08-15 20:51:30,Ao.dawson88@gmail.com\nPark on beech st \n4 ho...,NaN,NaN,NaN,...,2013-08-26 00:35:09,1455 kertner blvd apt526 92101 to 801 ash st a...,1.0,$65 $30 Alex Dawson 928-301-3402,0.0,OPAQUE,NaN,NaN,NaN,NaN
4,2013-08-20 15:00:00,2013-08-20 16:00:00,NaN,2016-11-29 12:31:58,uitttdtrjts4vermju9k0vtf5c@google.com,2013-08-18 00:58:34,"$15 wardrobes\n3 hours\, 3wardrobes \n15% $37.05",NaN,NaN,NaN,...,2013-08-26 00:39:28,707 10-th ave san diego ca 92101 to storage se...,2.0,Andrew Garry 860-705-4143 $65 $20 5% off,0.0,OPAQUE,NaN,NaN,NaN,NaN
5,2013-08-20 15:00:00,2013-08-20 16:00:00,NaN,2016-11-29 12:31:58,2i941ljktu1raatvg1dlgvk1h0@google.com,2013-08-19 18:57:51,Mazi7474@yahoo.com\n19.5 hrs ( 5% off)\n15%$20...,NaN,NaN,NaN,...,2013-08-26 00:40:42,3435 capri way unit 1 oceanside ca 92056 to 21...,1.0,Mahsa Ziadloo 760-846-5094 760-846-5097 $140 $65,0.0,OPAQUE,NaN,NaN,NaN,NaN
6,2013-08-20 21:00:00,2013-08-20 22:00:00,NaN,2016-11-29 12:31:58,222F6FB4-22EB-4FA2-890D-F661709D98D2,2013-08-19 21:16:00,3 hours\n15%$33.75,NaN,NaN,NaN,...,2013-08-26 00:41:21,#224 11549 Windcrest lane 92128 to storage.,0.0,Alene Mcbride 858-568-3848 $65 $30,0.0,OPAQUE,NaN,NaN,NaN,NaN
7,2013-08-21 17:00:00,2013-08-21 18:00:00,NaN,2016-11-29 12:31:58,btfvh5trm4924q1thqdedlaslg@google.com,2013-08-22 01:42:46,3 hours \n$31.5,NaN,NaN,NaN,...,2013-08-26 00:42:13,6586 embrosia dr #5405 san diego 92124,1.0,Daby Davis 702-715-5801 $65 $15,0.0,OPAQUE,NaN,NaN,NaN,NaN
8,2013-08-23 14:00:00,2013-08-23 15:00:00,NaN,2016-11-29 12:31:58,0g22cflo9jscgjlkedoeca7jd4@google.com,2013-08-23 01:47:30,mosb_33@hotmail.com\n3 hours\n$33.75,NaN,NaN,NaN,...,2013-08-26 00:42:50,6699 beadnell apt 241 san diego 92117 to 910 d...,0.0,Nouf Barasayn 858-717-3392 $65 $30,0.0,OPAQUE,NaN,NaN,NaN,NaN
9,2013-08-23 17:12:00,2013-08-23 18:12:00,NaN,2016-11-29 12:31:58,5FF5E7A1-4FD4-4B93-8107-C2033BC6D12E,2013-08-23 16:52:58,4 hr\n$44.25,NaN,NaN,NaN,...,2013-08-26 00:44:18,Carlos Mantoya 832-712-4685 $65 $35,0.0,Carlos Mantoya 832-712-4685 $65 $35,0.0,OPAQUE,NaN,NaN,NaN,NaN
10,2013-08-24 15:00:00,2013-08-24 16:00:00,NaN,2016-11-29 12:31:58,dg4ftugke2fv3dh734calcqocg@google.com,2013-08-17 06:38:59,4 hours total \n$49.5,NaN,NaN,NaN,...,2013-08-26 00:45:06,"from is 10954 West Ocean Air Drive\, #298\, Sa...",0.0,$75 $30gas Carri Schlade estimate 3-5 hours,0.0,OPAQUE,NaN,NaN,NaN,NaN
11,2013-08-24 16:00:00,2013-08-24 17:00:00,NaN,2016-11-29 12:31:58,7EA3113C-7465-492D-A89A-79A095DE81D4,2013-08-21 15:21:13,Malissastorer@gmail.com\n4.5 hr\n$63.225,NaN,NaN,NaN,...,2013-08-26 00:45:56,933 ruby dr Vista ca92083 to 841 rio claro cou...,0.0,$87 $30 gas Melissa Storer 760-805-1220,0.0,OPAQUE,NaN,NaN,NaN,NaN
12,2013-08-25 16:00:00,2013-08-25 17:00:00,NaN,2016-11-29 12:31:58,vq1lmtuvch1iaok65fj4c4bvms@google.com,2013-08-19 16:41:17,Ktran92126@yahoo.com\nDiscount is 10% movers g...,NaN,NaN,NaN,...,2013-08-26 00:47:13,11736 engelique st san diego 92131 to 862 wind...,1.0,$65 $40 5% off Kim Tran 858-610-3674,0.0,OPAQUE,NaN,NaN,NaN,NaN
13,2013-08-25 22:30:00,2013-08-25 23:30:00,NaN,2016-11-29 12:31:58,1f5bgc4fuak225e3octt1uktto@google.com,2013-08-17 21:50:46,3.5 hours\n$55.425,NaN,NaN,NaN,...,2013-08-26 00:49:35,"12704 Portofino Drive\, Del Mar 92014 to 3851 ...",1.0,3 movers $97/hr $30 gas charge Samantha Smith ...,0.0,OPAQUE,NaN,NaN,NaN,NaN
14,2013-08-26 00:00:00,2013-08-27 00:00:00,NaN,2016-11-29 12:31:58,B238950B-A3DA-45E9-A903-886E302CAE74,2013-08-26 00:51:51,NaN,NaN,NaN,NaN,...,2013-08-26 00:54:01,NaN,0.0,Send $625.00,0.0,OPAQUE,NaN,NaN,NaN,NaN
15,2013-08-26 16:00:00,2013-08-26 17:00:00,NaN,2016-11-29 12:31:58,262B41AE-F770-4235-8206-79DD7EDB10CA,2013-08-22 21:19:35,6.15 hr,NaN,NaN,NaN,...,2013-08-27 15:34:47,1639 regulus st 92111 to 9341 pastoria court 9...,1.0,$109/hr $30 gasOmar Farah 619-417-2302,0.0,OPAQUE,NaN,NaN,NaN,NaN
16,2013-08-26 19:00:00,2013-08-26 20:00:00,NaN,2016-11-29 12:31:58,3B79AE19-8AE7-40F0-9C09-7370D5E4D398,2013-08-23 19:32:22,4.5 hr,NaN,NaN,NaN,...,2013-08-27 15:35:10,514 greenbrier dr apt#4 Oceanside ca92054 to49...,1.0,Sarah Neary 805-674-4725 $65 $35 DDT,0.0,OPAQUE,NaN,NaN,NaN,NaN
17,2013-08-27 17:00:00,2013-08-27 18:00:00,NaN,2016-11-29 12:31:58,C335E20C-8BB7-4485-99B9-7E914C42FE44,2013-08-27 15:33:19,3 hr,NaN,NaN,NaN,...,2013-08-27 20:52:15,2966 briand ave 92122,0.0,Brian Pittman 619-203-7084 $65,0.0,OPAQUE,NaN,NaN,NaN,NaN
18,2013-08-30 15:00:00,2013-08-30 16:00:00,NaN,2016-11-29 12:31:58,1mimrk4c5gbv54mvs91jvvuits@google.com,2013-08-29 06:06:40,Marktlastname@gmail.com\n6 hours,NaN,NaN,NaN,...,2013-08-31 02:11:32,4515 4th st la mesa 91941 to 7515 el cajon blvd,1.0,Mark Pachpco 619-227-7660 $87 $20,0.0,OPAQUE,NaN,NaN,NaN,NaN
19,2013-09-15 22:30:00,2013-09-15 23:30:00,NaN,2016-11-29 12:31:58,8C0FDCDA-EB9C-41C2-8604-64756020BFEE,2013-08-30 17:53:33,NaN,NaN,NaN,NaN,...,2013-09-01 20:16:08,14738 shadowbrook court poway ca 92064 to 1096...,2.0,Marlo Willows 858-444-6437 $65 $30,0.0,OPAQUE,NaN,NaN,NaN,NaN
20,2013-09-01 15:00:00,2013-09-01 16:00:00,NaN,2016-11-29 12:31:58,E84EC599-1CBD-478C-BF37-E7275D359919,2013-08-29 23:45:36,Fadihassoun@cox.net\n3 hours,NaN,NaN,NaN,...,2013-09-02 15:16:22,7191 Eldridge San Diego 92120 to 2675 fletcher...,0.0,Hassoun Fadi 619-370-9885 $65$30,0.0,OPAQUE,NaN,NaN,NaN,NaN
21,2013-09-02 17:00:00,2013-09-02 18:00:00,NaN,2016-11-29 12:31:58,B9E2F081-21C1-4472-90D1-72B9ABA7F358,2013-09-01 19:57:28,Paul@lastnamerealty.com\n$215,NaN,NaN,NaN,...,2013-09-03 01:00:41,520 Stratford court del mar to 11247 Carmel cr...,0.0,$20 $65 Paul Galloway 858-461-9757,0.0,OPAQUE,NaN,NaN,NaN,NaN
22,2013-09-01 22:30:00,2013-09-01 23:30:00,NaN,2016-11-29 12:31:58,24F47128-20C0-434E-ADF2-DB249A056FDA,2013-08-31 22:00:16,Jtaoutozone2013@gmail.com\n$989,NaN,NaN,NaN,...,2013-09-03 01:05:26,4808 falconhurst terrace to spring valley,0.0,Jose Martinez 619-761-3227 $87 $40\; $152 $80,0.0,OPAQUE,NaN,NaN,NaN,NaN
23,2013-08-30 23:00:00,2013-08-31 00:00:00,NaN,2016-11-29 12:31:58,ak1j7ere041mhk17qi1t47mv08@google.com,2013-08-31 02:13:01,$355,NaN,NaN,NaN,...,2013-09-03 01:06:40,NaN,0.0,2 movers $65 $30,0.0,OPAQUE,NaN,NaN,NaN,NaN
24,2013-09-01 22:30:00,2013-09-01 23:30:00,NaN,2016-11-29 12:31:58,ca44nfvd9c6dd737l7ebtslrqo@google.com,2013-08-30 19:45:35,$225,NaN,NaN,NaN,...,2013-09-03 01:07:36,6955 Alvarado Rd San Diego 92120 #26 to,0.0,Steven Huynh 619-817-1607 $65 $30,0.0,OPAQUE,NaN,NaN,NaN,NaN
25,2013-09-01 15:00:00,2013-09-01 16:00:00,NaN,2016-11-29 12:31:58,E4D21F02-A7C1-497C-865D-668662A9E211,2013-08-29 22:23:32,$267,NaN,NaN,NaN,...,2013-09-03 01:08:50,3688 Georgia st San Diego 92103 to 154 rancho ...,0.0,$65 $40 Lori Smith 619-701-7479,0.0,OPAQUE,NaN,NaN,NaN,NaN
26,2013-08-30 19:00:00,2013-08-30 20:00:00,NaN,2016-11-29 12:31:58,4A84CD7A-9333-48FC-BFE1-8D622564DBC4,2013-08-30 16:19:34,Tracy_alkire@yahoo.com\n$737,NaN,NaN,NaN,...,2013-09-03 01:10:08,747 avocado ave el cajon #16 92020 to 425 east...,0.0,Tracy Alkire 360-961-8505. $75 $25,0.0,OPAQUE,NaN,NaN,NaN,NaN
27,2013-08-30 15:00:00,2013-08-30 16:00:00,NaN,2016-11-29 12:31:58,C624302A-0AB0-414D-A4E0-79340FE381EC,2013-08-23 19:28:34,3 hours\n$225,NaN,NaN,NaN,...,2013-09-03 01:10:57,5555 lake Murray blvd apt 37 91942 to 351 east...,0.0,$65 $30 Terry Weiss 805-433-3487,0.0,OPAQUE,NaN,NaN,NaN,NaN
28,2013-08-31 22:30:00,2013-08-31 23:30:00,NaN,2016-11-29 12:31:58,10986805-9959-4619-96C1-87D827867B5C,2013-08-29 16:41:06,Michael.j.link@gmail.com\n$649,NaN,NaN,NaN,...,2013-09-03 01:11:57,2375 ranching del oro rd #37 92056 gate#5945 t...,0.0,$87 $40 Michael Link 760-691-0893\; 760-453-2295,0.0,OPAQUE,NaN,NaN,NaN,NaN
29,2013-08-31 15:00:00,2013-08-31 16:00:00,NaN,2016-11-29 12:31:58,108E4D99-5CEE-42C4-AA2D-87F3AA4FFC6B,2013-08-16 19:19:32,Ton.tjoyce@gmail.com\n$432,NaN,NaN,NaN,...,2013-09-03 01:13:05,8730 costa verde blvd apt 2428 92122 to 7675 p...,1.0,Thomas Joyce 858-729-4206 $75 $20,0.0,OPAQUE,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3985,2016-11-30 21:00:00,2016-12-01 02:00:00,NaN,2016-11-29 12:31:59,or4183ese7h14arnahqk1tivp8@google.com,2016-11-28 23:10:38,"November 30\, 2016 1:00pm PST\nCalendar: Vecto...","4082 First Ave. San Diego\, Ca 92103",House,92103.0,...,2016-11-28 23:10:38,Vector Moving and Storage,0.0,Heather Stafford: Local Moving with approximat...,0.0,OPAQUE,32.751486,-117.163958,NaN,NaN
3986,2016-12-01 16:00:00,2016-12-01 21:00:00,NaN,2016-11-29 12:31:59,b8qun8k8s9pvaih43o0c1tomlk@google.com,2016-11-28 23:11:23,"December 1\, 2016 8:00am PST\nCalendar: Vector...","525 14th street #457 San Diego\, Ca 92101",Apartment,92101.0,...,2016-11-28 23:11:23,Vector Moving and Storage,0.0,Mary Redd: Local Moving with approximate durat...,0.0,OPAQUE,32.716535,-117.161019,NaN,NaN
3987,2016-12-01 17:00:00,2016-12-01 22:00:00,NaN,2016-11-29 12:31:59,djudnk9qv0ipdgkehutj2cjckk@google.com,2016-11-28 23:11:59,"December 1\, 2016 9:00am PST\nCalendar: Vector...","4945 haight trail San Diego\, ca 92123",Townhouse,92123.0,...,2016-11-28 23:11:59,Vector Moving and Storage,0.0,Roozy Taheri: Local Moving with approximate du...,0.0,OPAQUE,32.827466,-117.136871,NaN,NaN
3988,2016-12-01 17:00:00,2016-12-01 23:00:00,NaN,2016-11-29 12:31:59,n49jliks9dhfc2arek087uo6mk@google.com,2016-11-28 23:12:23,"December 1\, 2016 9:00am PST\nCalendar: Vector...","3376 Daley Center Dr. #1810 San Diego\, Ca 92123",Apartment,92123.0,...,2016-11-28 23:12:23,Vector Moving and Storage,0.0,Erwin Fontelera: Local Moving with approximate...,0.0,OPAQUE,32.804828,-117.118076,NaN,NaN
3989,2016-12-02 16:00:00,2016-12-02 21:00:00,NaN,2016-11-29 12:31:59,t58ojl1diiitngpujv0on20ndo@google.com,2016-11-28 23:12:40,"December 2\, 2016 8:00am PST\nCalendar: Vector...","3882 Jewell St. Apt G203 San Diego\, CA 92109",Apartment,92109.0,...,2016-11-28 23:12:40,Vector Moving and Storage,0.0,Chere Ventimiglia: Local Moving with approxima...,0.0,OPAQUE,32.790277,-117.236795,NaN,NaN
3990,2016-12-02 16:00:00,2016-12-02 21:00:00,NaN,2016-11-29 12:31:59,m83gthigenv3g0b2tekqcepq0k@google.com,2016-11-28 23:13:01,"December 2\, 2016 8:00am PST\nCalendar: Vector...","26671 Littlepage Ln Ramona\, CA 92065",House,92065.0,...,2016-11-28 23:13:01,Vector Moving and Storage,0.0,Denice Writesel: Local Moving with approximate...,0.0,OPAQUE,33.049514,-116.753689,NaN,NaN
3991,2016-12-02 16:00:00,2016-12-02 21:00:00,NaN,2016-11-29 12:31:59,lo6ul80inggt4n11p1bofh1670@google.com,2016-11-28 23:13:18,"December 2\, 2016 8:00am PST\nCalendar: Vector...","2221 Polk Ave. San Diego\, CA 92104",Condo,92104.0,...,2016-11-28 23:13:18,Vector Moving and Storage,0.0,Jamie Lawler: Local Moving with approximate du...,0.0,OPAQUE,32.751996,-117.140798,NaN,NaN
3992,2016-12-02 16:00:00,2016-12-02 21:00:00,NaN,2016-11-29 12:31:59,fro9sd2rdqjcorplv094b37ueo@google.com,2016-11-28 23:13:38,"December 2\, 2016 8:00am PST\nCalendar: Vector...","4049 Arroyo Sorrento Rd\, San Diego\, CA 92130",House,92130.0,...,2016-11-28 23:13:38,Vector Moving and Storage,0.0,Mike Brown: Local Moving with approximate dura...,0.0,OPAQUE,32.928585,-117.228089,NaN,NaN
3993,2016-12-02 21:00:00,2016-12-03 02:00:00,NaN,2016-11-29 12:31:59,1nn2ksv1g5hu8rtml013lrnkv4@google.com,2016-11-28 23:13:54,"December 2\, 2016 1:00pm PST\nCalendar: Vector...","1230 23rd St. San Diego\, Ca 92102",Condo,92102.0,...,2016-11-28 23:13:54,Vector Moving and Storage,0.0,Lauren Gray: Local Moving with approximate dur...,0.0,OPAQUE,32.772905,-117.062005,NaN,NaN
3994,2016-12-03 16:00:00,2016-12-03 21:00:00,NaN,2016-11-29 12:31:59,vpd1210bkrr2nb8c26qto7954c@google.com,2016-11-28 23:14:51,"December 3\, 2016 8:00am PST\nCalendar: Vector...","8465 Regents Rd. #103 San Diego\, Ca 92121",Apartment,92121.0,...,2016-11-28 23:14:51,Vector Moving and Storage,0.0,David Fong: Local Moving with approximate dura...,0.0,OPAQUE,32.878759,-117.218338,NaN,NaN
3995,2016-12-03 15:00:00,2016-12-03 20:00:00,NaN,2016-11-29 12:31:59,dahjmadrhill1itojnhdpk9844@google.com,2016-11-28 23:15:14,"December 3\, 2016 7:00am PST\nCalendar: Vector...","2014 Oliver Ave. #7 San Diego \, Ca 92109",Apartment,92109.0,...,2016-11-28 23:15:14,Vector Moving and Storage,0.0,Matt Mcalughlin: Local Moving with approximate...,0.0,OPAQUE,32.797005,-117.231796,NaN,NaN
3996,2016-12-03 16:00:00,2016-12-04 00:00:00,NaN,2016-11-29 12:31:59,g7j1apvgcbordpen6vei08705o@google.com,2016-11-28 23:15:32,"December 3\, 2016 8:00am PST\nCalendar: Vector...","1052 Law St. San Diego\, Ca 92109",House,92109.0,...,2016-11-28 23:15:32,Vector Moving and Storage,0.0,Sean Smith: Local Moving with approximate dura...,0.0,OPAQUE,32.803504,-117.252487,NaN,NaN
3997,2016-12-03 17:00:00,2016-12-03 22:00:00,NaN,2016-11-29 12:31:59,sel19226pmlfmvjo4chaakkrc8@google.com,2016-11-28 23:16:06,"December 3\, 2016 9:00am PST\nCalendar: Vector...","7845 Westside Dr. #501 San Diego\, Ca 92108",Apartment,92108.0,...,2016-11-28 23:16:06,Vector Moving and Storage,0.0,Courtney Washington: Local Moving with approxi...,0.0,OPAQUE,32.776369,-117.151701,NaN,NaN
3998,2016-12-05 16:00:00,2016-12-06 01:00:00,NaN,2016-11-29 12:31:59,t2gssl2fdvn710prn7v9lvalfk@google.com,2016-11-28 23:16:52,"December 5\, 2016 8:00am PST\nCalendar: Vector...","1660 Copper Penny Dr. Chula Vista\, Ca 91915",House,91915.0,...,2016-11-28 23:16:52,Vector Moving and Storage,0.0,Joseph Adato: Local Moving with approximate du...,0.0,OPAQUE,32.626072,-116.949308,NaN,NaN
3999,2016-12-07 16:00:00,2016-12-07 21:00:00,NaN,2016-11-29 12:31:59,mk8luv4cvckren8f9sul46nuro@google.com,2016-11-28 23:17:03,"December 7\, 2016 8:00am PST\nCalendar: Vector...","12485 Brickellia St. San Diego\, Ca 92129",House,92129.0,...,2016-11-28 23:17:03,Vector Moving and Storage,0.0,Tina Rountree: Local Moving with approximate d...,0.0,OPAQUE,32.948508,-117.138768,NaN,NaN
4000,2016-12-08 16:00:00,2016-12-09 00:00:00,NaN,2016-11-29 12:31:59,rahcs191haaqb7fn86kfbrg6kk@google.com,2016-11-28 23:17:15,"December 8\, 2016 8:00am PST\nCalendar: Vector...","3085 Karnes Way\, San Diego Ca 92117",House,92117.0,...,2016-11-28 23:17:15,Vector Moving and Storage,0.0,Ramlah Nehring: Local Moving with approximate ...,0.0,OPAQUE,32.816765,-117.217240,NaN,NaN
4001,2016-12-09 16:00:00,2016-12-09 21:00:00,NaN,2016-11-29 12:31:59,5e6vh9h8h4t5gquhp5rpe05bjo@google.com,2016-11-28 23:17:26,"December 9\, 2016 8:00am PST\nCalendar: Vector...","4170 Porte De Palmas #18 San Diego\, Ca 92122",Condo,92122.0,...,2016-11-28 23:17:26,Vector Moving and Storage,0.0,Michelle Lee: Local Moving with approximate du...,0.0,OPAQUE,32.860457,-117.224780,NaN,NaN
4002,2016-12-11 16:00:00,2016-12-12 00:00:00,NaN,2016-11-29 12:31:59,a8ed2gtk5nou5qekb5tsicf8ns@google.com,2016-11-28 23:17:53,"December 11\, 2016 8:00am PST\nCalendar: Vecto...","5365 Toscana Way #415 San Diego\, CA 92122",Condo,92122.0,...,2016-11-28 23:17:53,Vector Moving and Storage,0.0,Praveen Nair: Local Moving with approximate du...,0.0,OPAQUE,32.869378,-117.201735,NaN,NaN
4003,2016-12-15 16:00:00,2016-12-15 21:00:00,NaN,2016-11-29 12:31:59,tb1d4h5ulsj4irpf4flnsia8tk@google.com,2016-11-28 23:18:23,"December 15\, 2016 8:00am PST\nCalendar: Vecto...","1080 Park Blvd. #701 San Diego\, Ca 92101",Apartment,92101.0,...,2016-11-28 23:18:23,Vector Moving and Storage,0.0,Jack Ward: Local Moving with approximate durat...,0.0,OPAQUE,32.716388,-117.154124,NaN,NaN
4004,2016-12-17 16:00:00,2016-12-17 21:00:00,NaN,2016-11-29 12:31:59,dugn355d3pjj3ugap3q0bhdu5o@google.com,2016-11-28 23:18:41,"December 17\, 2016 8:00am PST\nCalendar: Vecto...","3969 Adams St. #A101 Carlsbad\, Ca 92008",Apartment,92008.0,...,2016-11-28 23:18:41,Vector Moving and Storage,0.0,Ray Ramirez: Local Moving with approximate dur...,0.0,OPAQUE,33.151824,-117.333096,NaN,NaN
4005,2016-12-31 17:00:00,2016-12-31 23:00:00,NaN,2016-11-29 12:31:59,oqqfv95ph08dut9ghdpqeseeds@google.com,2016-11-28 23:19:12,"December 31\, 2016 9:00am PST\nCalendar: Vecto...","2850 Kelvin Ave\, Irvine\, CA 92614",Apartment,92614.0,...,2016-11-28 23:19:12,Vector Moving and Storage,0.0,Jack Arndt: Local Moving with approximate dura...,0.0,OPAQUE,33.683444,-117.837051,NaN,NaN
4006,2016-11-30 01:00:00,2016-11-30 02:00:00,NaN,2016-11-29 12:31:59,oulnd3snc83i2ivn0vvujvqse4@google.com,2016-11-28 23:41:24,Moving Date:December 8 or 9.\n4 beds 3 baths 2...,NaN,NaN,NaN,...,2016-11-28 23:41:24,"551 Chandler Ct\, Escondido\, CA 92027\, USA",0.0,5-5:30 pm Venise Jane 858-243-3117,0.0,OPAQUE,NaN,NaN,NaN,NaN
4007,2016-11-30 17:30:00,2016-11-30 18:30:00,NaN,2016-11-29 12:31:59,e48ml911ifh8jjqliev0iu25ec@google.com,2016-11-28 19:03:10,"702-797-0460 \n1341 San Elijo Cardiff\, CA 920...",NaN,NaN,NaN,...,2016-11-28 23:43:34,NaN,0.0,Estimate Jason Vallante,0.0,OPAQUE,NaN,NaN,NaN,NaN
4008,2016-11-29 19:00:00,2016-11-30 00:00:00,NaN,2016-11-29 12:31:59,r4p3n3fkjn5d0h3vu7579sf9rs@google.com,2016-11-29 00:50:12,"November 29\, 2016 11:00am PST\nCalendar: Vect...","8875 Costa Verde Blvd #1209 San Diego\, Ca 92122",Apartment,92122.0,...,2016-11-29 00:50:12,Vector Moving and Storage,0.0,Talma Kowsky: Local Moving with approximate du...,0.0,OPAQUE,32.870110,-117.215836,NaN,NaN
4009,2016-12-01 22:00:00,2016-12-02 06:00:00,NaN,2016-11-29 12:31:59,mseq63sf79542ehq1isoq6mg94@google.com,2016-11-29 00:57:30,"December 1\, 2016 2:00pm PST\nCalendar: Vector...","2870 Fifth Ave. Suite 107 San Diego\, Ca 92103",Office,92103.0,...,2016-11-29 00:57:30,Vector Moving and Storage,0.0,Shawn Fisher: Local Moving with approximate du...,0.0,OPAQUE,32.735400,-117.160362,NaN,NaN
4010,2016-09-06 08:00:00,2016-09-06 16:00:00,NaN,2016-11-29 12:31:59,oqfubfu24hikhilbdfoi32gcco@google.com,2015-10-07 19:11:08,NAME:\nPHONE:\nEMAIL: \nBOOKED BY: \n\nORIGIN:...,NaN,NaN,NaN,...,2016-10-15 21:37:15,NaN,6.0,[3men] Chris Baechli,0.0,OPAQUE,NaN,NaN,NaN,NaN
4011,2016-11-16 07:00:00,2016-11-16 08:00:00,NaN,2016-11-29 12:31:59,ptu1buvejh0lv07hobjdhljnu8_R20161102T140000@go...,2016-10-25 19:17:28,Drivers:\n1. Jimmy P\n2. Ruben R\n3. Matthew J...,NaN,NaN,NaN,...,2016-11-16 14:50:21,NaN,1.0,15 people: 6 drivers 9 helpers,0.0,OPAQUE,NaN,NaN,NaN,NaN
4012,2016-11-02 07:00:00,2016-11-02 08:00:00,FREQ=WEEKLY;BYDAY=WE,2016-11-29 12:31:59,ptu1buvejh0lv07hobjdhljnu8_R20161102T140000@go...,2016-10-25 19:17:28,Drivers:\n1. Jimmy P\n2. Ruben R\n3. Matthew J...,NaN,NaN,NaN,...,2016-11-14 22:23:23,NaN,1.0,15 people: 6 drivers 9 helpers,0.0,OPAQUE,NaN,NaN,NaN,NaN
4013,2016-11-18 07:00:00,2016-11-18 08:00:00,NaN,2016-11-29 12:31:59,c80g7urv1islj6ji2jfhdq886s_R20161104T140000@go...,2016-10-25 19:18:48,Drivers:\n1. Jimmy P\n2. Ruben R\n3. Christian...,NaN,NaN,NaN,...,2016-11-18 14:39:31,NaN,1.0,17 people: 7 drivers 10 helpers,0.0,OPAQUE,NaN,NaN,NaN,NaN

In [32]:
jobs_df[['ORIGIN', 'LOCATION']]

,ORIGIN,LOCATION
0,NaN,972 broadway 91911 building bihind 970 to 2811...
1,NaN,7864 avenida navidad San Diego 92122 #195 to 8...
2,NaN,NaN
3,NaN,1455 kertner blvd apt526 92101 to 801 ash st a...
4,NaN,707 10-th ave san diego ca 92101 to storage se...
5,NaN,3435 capri way unit 1 oceanside ca 92056 to 21...
6,NaN,#224 11549 Windcrest lane 92128 to storage.
7,NaN,6586 embrosia dr #5405 san diego 92124
8,NaN,6699 beadnell apt 241 san diego 92117 to 910 d...
9,NaN,Carlos Mantoya 832-712-4685 $65 $35
10,NaN,"from is 10954 West Ocean Air Drive\, #298\, Sa..."
11,NaN,933 ruby dr Vista ca92083 to 841 rio claro cou...
12,NaN,11736 engelique st san diego 92131 to 862 wind...
13,NaN,"12704 Portofino Drive\, Del Mar 92014 to 3851 ..."
14,NaN,NaN
15,NaN,1639 regulus st 92111 to 9341 pastoria court 9...
16,NaN,514 greenbrier dr apt#4 Oceanside ca92054 to49...
17,NaN,2966 briand ave 92122
18,NaN,4515 4th st la mesa 91941 to 7515 el cajon blvd
19,NaN,14738 shadowbrook court poway ca 92064 to 1096...
20,NaN,7191 Eldridge San Diego 92120 to 2675 fletcher...
21,NaN,520 Stratford court del mar to 11247 Carmel cr...
22,NaN,4808 falconhurst terrace to spring valley
23,NaN,NaN
24,NaN,6955 Alvarado Rd San Diego 92120 #26 to
25,NaN,3688 Georgia st San Diego 92103 to 154 rancho ...
26,NaN,747 avocado ave el cajon #16 92020 to 425 east...
27,NaN,5555 lake Murray blvd apt 37 91942 to 351 east...
28,NaN,2375 ranching del oro rd #37 92056 gate#5945 t...
29,NaN,8730 costa verde blvd apt 2428 92122 to 7675 p...
...,...,...
3985,"4082 First Ave. San Diego\, Ca 92103",Vector Moving and Storage
3986,"525 14th street #457 San Diego\, Ca 92101",Vector Moving and Storage
3987,"4945 haight trail San Diego\, ca 92123",Vector Moving and Storage
3988,"3376 Daley Center Dr. #1810 San Diego\, Ca 92123",Vector Moving and Storage
3989,"3882 Jewell St. Apt G203 San Diego\, CA 92109",Vector Moving and Storage
3990,"26671 Littlepage Ln Ramona\, CA 92065",Vector Moving and Storage
3991,"2221 Polk Ave. San Diego\, CA 92104",Vector Moving and Storage
3992,"4049 Arroyo Sorrento Rd\, San Diego\, CA 92130",Vector Moving and Storage
3993,"1230 23rd St. San Diego\, Ca 92102",Vector Moving and Storage
3994,"8465 Regents Rd. #103 San Diego\, Ca 92121",Vector Moving and Storage
3995,"2014 Oliver Ave. #7 San Diego \, Ca 92109",Vector Moving and Storage
3996,"1052 Law St. San Diego\, Ca 92109",Vector Moving and Storage
3997,"7845 Westside Dr. #501 San Diego\, Ca 92108",Vector Moving and Storage
3998,"1660 Copper Penny Dr. Chula Vista\, Ca 91915",Vector Moving and Storage
3999,"12485 Brickellia St. San Diego\, Ca 92129",Vector Moving and Storage
4000,"3085 Karnes Way\, San Diego Ca 92117",Vector Moving and Storage
4001,"4170 Porte De Palmas #18 San Diego\, Ca 92122",Vector Moving and Storage
4002,"5365 Toscana Way #415 San Diego\, CA 92122",Vector Moving and Storage
4003,"1080 Park Blvd. #701 San Diego\, Ca 92101",Vector Moving and Storage
4004,"3969 Adams St. #A101 Carlsbad\, Ca 92008",Vector Moving and Storage
4005,"2850 Kelvin Ave\, Irvine\, CA 92614",Vector Moving and Storage
4006,NaN,"551 Chandler Ct\, Escondido\, CA 92027\, USA"
4007,NaN,NaN
4008,"8875 Costa Verde Blvd #1209 San Diego\, Ca 92122",Vector Moving and Storage
4009,"2870 Fifth Ave. Suite 107 San Diego\, Ca 92103",Vector Moving and Storage
4010,NaN,NaN
4011,NaN,NaN
4012,NaN,NaN
4013,NaN,NaN
4014,NaN,NaN