Adding Features to the Datasets Provided

In [1]:
import pandas as pd

In [2]:
schedule = pd.read_csv('Republican_primary_schedule.csv')

In [14]:
lst = []
for i in schedule['state']:
    i = i.replace("_"," ")
    lst.append(i)

In [15]:
schedule['state'] = lst

In [16]:
timezones = pd.read_csv('timezones.csv')

In [17]:
new = schedule.merge(timezones, how='left', left_on='state', right_on='State Name')

In [18]:
#Samoa Standard Time
#guam - chamorro
#district eastern

In [20]:
new = new.drop(columns=['State Name'])

In [22]:
new = new.rename(columns={'Time Zone(s)': 'timezone'})

In [43]:
new.loc[new.state=='American Samoa','timezone'] = 'Samoa Standard Time'
new.loc[new.state=='District of Columbia','timezone'] = 'Eastern Time Zone'
new.loc[new.state=='Guam','timezone'] = 'Chomorro'
new.loc[new.state=='Northern Marianas','timezone'] = 'Chomorro'
new.loc[new.state=='Virgin Islands','timezone'] = 'Atlantic Standard Time'
new.loc[new.state=='Puerto Rico','timezone'] = 'Atlantic Standard Time'

In [45]:
lst = []
for i in new['timezone']:
    string = i.split(',')
    if len(string)>1:
        string.pop(1)
    lst.append(string)
flat_list = [item for sublist in lst for item in sublist]

In [47]:
new['timezone'] = flat_list

In [55]:
lst = []
for i, k in zip(new['month'],new['day']):
    if i == 'March':
        m = '3'
    elif i == 'April':
        m = '4'
    elif i == 'May':
        m = '5'
    elif i == 'June':
        m = '6'
    elif i == 'February':
        m = '2'
    dat = str(m) + '-' + str(k) + '-' + '2017'
    lst.append(dat)

In [57]:
new['date'] = lst

In [58]:
new['date'] = pd.to_datetime(new['date'])

In [61]:
new.to_csv('newschedule.csv')

In [60]:
new

                   state     month  day                   timezone       date
0                Alabama     March    1          Central Time Zone 2017-03-01
1                 Alaska     March    1           Alaska Time Zone 2017-03-01
2         American Samoa     March    8        Samoa Standard Time 2017-03-08
3               Arkansas     March    1          Central Time Zone 2017-03-01
4                Arizona     March   22         Mountain Time Zone 2017-03-22
5             California      June    7          Pacific Time Zone 2017-06-07
6               Colorado     March    1         Mountain Time Zone 2017-03-01
7            Connecticut     April   26          Eastern Time Zone 2017-04-26
8               Delaware     April   26          Eastern Time Zone 2017-04-26
9   District of Columbia      June   14          Eastern Time Zone 2017-06-14
10               Florida     March   15          Eastern Time Zone 2017-03-15
11               Georgia     March    1          Eastern Time Zone 2017-03-01
12                  Guam     March   12                   Chomorro 2017-03-12
13                Hawaii     March    8  Hawaii-Aleutian Time Zone 2017-03-08
14                 Idaho     March    8         Mountain Time Zone 2017-03-08
15              Illinois     March   15          Central Time Zone 2017-03-15
16               Indiana       May    3          Eastern Time Zone 2017-05-03
17                  Iowa  February    1          Central Time Zone 2017-02-01
18              Kentucky     March    5          Eastern Time Zone 2017-03-05
19                Kansas     March    5          Central Time Zone 2017-03-05
20             Louisiana     March    5          Central Time Zone 2017-03-05
21                 Maine     March    5          Eastern Time Zone 2017-03-05
22              Maryland     April   26          Eastern Time Zone 2017-04-26
23         Massachusetts     March    1          Eastern Time Zone 2017-03-01
24              Michigan     March    8          Eastern Time Zone 2017-03-08
25             Minnesota     March    1          Central Time Zone 2017-03-01
26           Mississippi     March    8          Central Time Zone 2017-03-08
27              Missouri     March   15          Central Time Zone 2017-03-15
28               Montana      June    7         Mountain Time Zone 2017-06-07
29              Nebraska       May   10          Central Time Zone 2017-05-10
30                Nevada  February   23          Pacific Time Zone 2017-02-23
31         New Hampshire  February    9          Eastern Time Zone 2017-02-09
32            New Jersey      June    7          Eastern Time Zone 2017-06-07
33            New Mexico      June    7         Mountain Time Zone 2017-06-07
34              New York     April   19          Eastern Time Zone 2017-04-19
35        North Carolina     March   15          Eastern Time Zone 2017-03-15
36          North Dakota     March    1          Central Time Zone 2017-03-01
37     Northern Marianas     March   15                   Chomorro 2017-03-15
38                  Ohio     March   15          Eastern Time Zone 2017-03-15
39              Oklahoma     March    1          Central Time Zone 2017-03-01
40                Oregon       May   17          Pacific Time Zone 2017-05-17
41          Pennsylvania     April   26          Eastern Time Zone 2017-04-26
42           Puerto Rico     March   13     Atlantic Standard Time 2017-03-13
43          Rhode Island     April   26          Eastern Time Zone 2017-04-26
44        South Carolina  February   20          Eastern Time Zone 2017-02-20
45          South Dakota      June    7          Central Time Zone 2017-06-07
46             Tennessee     March    1          Eastern Time Zone 2017-03-01
47                 Texas     March    1          Central Time Zone 2017-03-01
48                  Utah     March   22         Mountain Time Zone 2017-03-22
49               Vermont     March    1          Eastern Time Zone 2017-03-01
50        Virgin Islands     March   12     Atlantic Standard Time 2017-03-12
51              Virginia     March    1          Eastern Time Zone 2017-03-01
52            Washington       May   24          Pacific Time Zone 2017-05-24
53         West Virginia       May   10          Eastern Time Zone 2017-05-10
54             Wisconsin     April    5          Central Time Zone 2017-04-05
55               Wyoming     March    1         Mountain Time Zone 2017-03-01